name: CI / CD - .NET Build and GitHub Pages Deploy

env:
  buildConfiguration: 'Release'
  solutionRootDirectory: './src/DegreeClassEstimator.sln'
  appDirectory: './src/Web/Web.csproj'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # This allows us to run the jobs manually from Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: 6.0.x
 
      - name: Restore
        run: dotnet restore ${{ env.solutionRootDirectory }} 
 
      - name: Build
        run: dotnet build ${{ env.solutionRootDirectory }}  --configuration ${{ env.buildConfiguration }}  --no-restore
 
      - name: Test
        run: dotnet test ${{ env.solutionRootDirectory }} --no-restore

      - name: Publish
        run: dotnet publish ${{ env.appDirectory }}  -c ${{ env.buildConfiguration }} -o release --no-restore

      # Change <base href="/" /> in index.html from / to include the repo name subdirectory
      # Otherwise the app tries to fetch resources from the site root (e.g. username.github.io/) rather than the subdirectory which GitHub Pages uses for the route
      - name: Change base tag in index.html to include the repo name subdirectory
        run: sed -i 's/<base href="\/" \/>/<base href="\/degree-class-estimator\/" \/>/g' release/wwwroot/index.html
    
      # .nojekyll tells GitHub pages to not treat this as a Jekyll project
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages-dev
          FOLDER: release/wwwroot
